spring:
    servlet:
      multipart:
          max-file-size: 2MB
          max-request-size: 10MB
    profiles:
#        active: '@profileName@'
        active: dev
#        active: '@profileName@'
#        active: dev

registration:
    enabled: true

management:
    endpoint:
        shutdown:
            enabled: false
    endpoints:
        web:
            exposure:
                include: "*"



mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.entity.po
    configuration:
        map-underscore-to-camel-case: true
